name: Build and Test Copy Command

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: CMake Build (Windows)
      if: matrix.os == 'windows-latest'
      uses: threeal/cmake-action@v2.0.0
      with:
        source-dir: copy_command
        build-dir: copy_command/build
        run-build: true
        build-args: --config Release

    - name: CMake Build (Linux/Mac)
      if: matrix.os != 'windows-latest'
      uses: threeal/cmake-action@v2.0.0
      with:
        source-dir: copy_command
        build-dir: copy_command/build
        run-build: true

    - name: CTest Test (Windows)
      if: matrix.os == 'windows-latest'
      uses: threeal/ctest-action@v1.1.0
      with:
        test-dir: copy_command/build
        args: -C Release
  
    - name: CTest Test (Linux/Mac)
      uses: threeal/ctest-action@v1.1.0
      with:
        test-dir: copy_command/build
