name: Build and Test Copy Command

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@latest
      
    - name: CMake Action
      uses: threeal/cmake-action@v2.0.0

    - name: Configure CMake
      run: cmake -S copy_command -B copy_command/build

    - name: Build with CMake
      run: cmake --build copy_command/build

    - name: Run tests with CTest
      run: ctest --output-on-failure
      working-directory: copy_command/build
