name: Build and Test Copy Command

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    env:
      BUILD_TYPE: Release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: CMake Build
      uses: threeal/cmake-action@v2.0.0
      with:
        source-dir: copy_command
        build-dir: copy_command/build
        run-build: true
        build-args: ${{ matrix.os == 'windows-latest' && '--config' }} ${{ matrix.os == 'windows-latest' && env.BUILD_TYPE }}

    - name: CTest Test
      uses: threeal/ctest-action@v1.1.0
      with:
        test-dir: copy_command/build
        args: ${{ matrix.os == 'windows-latest' && '-C' }} ${{ matrix.os == 'windows-latest' && env.BUILD_TYPE }}

